version: 2.1
jobs:
  compile:
    docker:
      - image: wizardprjkt/build:kernel
    steps:
      - run:
          shell: /bin/bash
          command: |
            git clone --depth=1 -b new --single-branch https://$AWAL:$AKHIR@github.com/sotodrom/kernel_qcom_sdm660 kernel
            curl -s -L https://raw.githubusercontent.com/texascake/cooking-kernel/rel/build.sh | bash
          no_output_timeout : 30m
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
